BUILD: Resync rpmbuild-docker script

diff --git a/rpmbuild-docker b/rpmbuild-docker
--- a/rpmbuild-docker
+++ b/rpmbuild-docker
@@ -57,6 +57,7 @@ declare SOURCEDIR=$SOURCEDIR
 declare OUTPUTDIR=$OUTPUTDIR
 declare PREBUILDSCRIPT=$PREBUILDSCRIPT
 declare DOWNLOAD=1
+declare RPMOPTS=()
 declare RPMBUILDOPTS=()
 declare RPMSPECOPTS=()
 
@@ -104,8 +105,7 @@ done
 
 [[ $XDEBUG == 1 ]] && set -x
 
-RPMBUILDOPTS+=( "$@" )
-RPMSPECOPTS+=( "$@" )
+RPMOPTS+=( "$@" )
 
 declare SPECFILE=${ARGS[0]}
 [[ ${SPECFILE:0:1} != "/" ]] && SPECFILE=$PWD/$SPECFILE
@@ -139,23 +139,27 @@ if [[ -z $SOURCEDIR && -d ${SPECDIR%/*}/SOURCES ]] ; then
   SOURCEDIR=${SPECDIR%/*}/SOURCES
 fi
 
-if [[ -z $PREBUILDSCRIPT ]]; then
+if [[ -n $PREBUILDSCRIPT ]]; then
+  [[ ${PREBUILDSCRIPT:0:1} == / ]] || PREBUILDSCRIPT="$PWD/$PREBUILDSCRIPT"
+elif [[ -z $PREBUILDSCRIPT ]]; then
   # auto locate prebuild script if not given
-  if [[ -x $SPECDIR/prebuild.sh ]]; then
-    PREBUILDSCRIPT=$SPECDIR/prebuild.sh
-    PREBUILDSCRIPTFILE=prebuild.sh
-  elif [[ -x ${SPECDIR%/*}/prebuild.sh ]]; then
-    PREBUILDSCRIPT=${SPECDIR%/*}/prebuild.sh
-    PREBUILDSCRIPTFILE=prebuild.sh
-  else
-    PREBUILDSCRIPTFILE=
-  fi
-else
-  if [[ ! -x $PREBUILDSCRIPT ]]; then
-    echo "FATAL: cannot execute prebuild script: $PREBUILDSCRIPT" >&2
+  for dir in "$SPECDIR" "$PWD"; do
+    for ext in sh inc; do
+      if [[ -e "$dir/prebuild.$ext" ]]; then
+        PREBUILDSCRIPT="$dir/prebuild.$ext"
+        break 2
+      fi
+    done
+  done
+fi
+if [[ -n $PREBUILDSCRIPT ]]; then
+  if [[ ! -r $PREBUILDSCRIPT ]]; then
+    echo "FATAL: can't open $PREBUILDSCRIPT for reading" >&2
+    exit 1
+  elif [[ ${PREBUILDSCRIPT##*.} == .sh && ! -x $PREBUILDSCRIPT ]]; then
+    echo "FATAL: prebuild script $PREBUILDSCRIPT not executable" >&2
     exit 1
   fi
-  PREBUILDSCRIPTFILE=${PREBUILDSCRIPT##*/}
 fi
 
 [[ -z $SOURCEDIR ]] && SOURCEDIR=$PWD
@@ -214,6 +218,7 @@ function dockerfile_for_dist_el7() {
 FROM centos:7
 RUN set -x && \
     ulimit -n 1024 && \
+    sed -i -re 's,mirror\.centos\.org,vault.centos.org,; s,^(mirrorlist),#\1,; s,^#(baseurl),\1,' /etc/yum.repos.d/CentOS-*.repo && \
     yum update -y && \
     yum install -y createrepo gcc make rpm-build && \
     echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf && \
@@ -413,12 +418,12 @@ if [[ -n $REPO ]] ; then
 fi
 
 if [[ -n $PREBUILDSCRIPT ]] ; then
-  DOCKER_OPTS+=( --mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/$PREBUILDSCRIPTFILE" )
+  DOCKER_OPTS+=( --mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/${PREBUILDSCRIPT##*/}" )
 fi
 
 
 function build_exit() {
-  local status=${1:-0}
+  local status=${?:-0}
   [[ -n $NOKEEP ]] && exit "$status"
   [[ -n $KEEP || $status != 0 ]] && sleep infinity
   exit "$status"
@@ -443,7 +448,8 @@ function build_dl() {
   fi
 }
 function build_main() {
-  set -fx
+  set -fxe
+  trap build_exit EXIT
   OIFS=$IFS
 
   mkdir -p "$BHOME"
@@ -463,20 +469,17 @@ EOF
     fi
   fi
 
-  if [[ -n $PREBUILDSCRIPTFILE ]] ; then
-    "/tmp/$PREBUILDSCRIPTFILE" || build_exit $?
+  if [[ -n $PREBUILDSCRIPT ]]; then
+    case "$PREBUILDSCRIPT" in
+      *.sh) "/tmp/$PREBUILDSCRIPT" ;;
+      *.inc) source "/tmp/$PREBUILDSCRIPT" ;;
+      *) echo 'Invalid prebuild script/source file'; exit 1 ;;
+    esac
   fi
 
-  rpmbuildopts=(
-    --define '_topdir /tmp/../tmp/../tmp'
-    --define "dist .$DIST"
-    "${RPMBUILDOPTS[@]}"
-  )
-  rpmspecopts=(
-    --define '_topdir /tmp/../tmp/../tmp'
-    --define "dist .$DIST"
-    "${RPMSPECOPTS[@]}"
-  )
+  RPMOPTS+=(  --define '_topdir /tmp/../tmp/../tmp' )
+  rpmbuildopts=( "${RPMOPTS[@]}" "${RPMBUILDOPTS[@]}" )
+  rpmspecopts=( "${RPMOPTS[@]}" "${RPMSPECOPTS[@]}" )
 
   IFS=$'\n'
   buildreq=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
@@ -485,7 +488,7 @@ EOF
     sed -re 's/^ *([^ ]( +[^ ]|[^ ])*) *$/\1/') )
   IFS=$OIFS
   if [[ -n $buildreq ]]; then
-    yum install -y "${buildreq[@]}" || build_exit $?
+    yum install -y "${buildreq[@]}"
   fi
 
   # download sources if needed
@@ -493,14 +496,13 @@ EOF
     dlsources=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
       sed -nr -e 's,^(source|patch)[0-9]*\s*:\s*(\S+).*,\2,i;T;/:\/\//p') )
     for i in "${dlsources[@]}"; do
-        RUNAS="$BUSER" build_dl "$i" /tmp/SOURCES || build_exit $?
+        RUNAS="$BUSER" build_dl "$i" /tmp/SOURCES
     done
   fi
 
   # Having _topdir /tmp causes problems in el6/el7 because it is not long enough
   # https://access.redhat.com/solutions/1426113
-  build_runas "$BUSER" rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE" ||
-      build_exit $?
+  build_runas "$BUSER" rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE"
 
   if [[ -n $REPO && -n $UPDATE ]] ; then
     for repo in RPMS SRPMS; do
@@ -508,7 +510,6 @@ EOF
       build_runas "$BUSER" createrepo --update "/tmp/local-repo/$repo"
     done
   fi
-  build_exit 0
 }
 
 # Build RPM in the container
@@ -516,7 +517,8 @@ CTNAME="build_${RANDOM}${RANDOM}${RANDOM}${RANDOM}"
 DOCKER_OPTS+=( --name "$CTNAME" -i --rm )
 trap 'docker kill "$CTNAME"; exit;' INT
 cat <<__EOF__ |docker run "${DOCKER_OPTS[@]}" "$IMAGE" /bin/bash &
-$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP PREBUILDSCRIPTFILE REPO RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE)
+$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE)
+$(printf 'PREBUILDSCRIPT=%q\n' "${PREBUILDSCRIPT##*/}")
 $(declare -f build_exit)
 $(declare -f build_runas)
 $(declare -f build_dl)
