MINOR: es-inject-json: Configurable error file including failed input

diff --git a/opt/logcenter/bin/es-inject-json b/opt/logcenter/bin/es-inject-json
--- a/opt/logcenter/bin/es-inject-json
+++ b/opt/logcenter/bin/es-inject-json
@@ -4,7 +4,9 @@
 # cat objects.ndjson |es-inject-json - my-index
 # cat objects.ndjson |es-inject-json - logs-my-datastream create
 
+export LC_ALL=C
 PROGNAME=${0##*/}
+TEMP_FILE="${TMPDIR:-/dev/shm}/${PROGNAME}.$(date +%s).${RANDOM}"
 
 function exit_usage() {
     local status=${1:-1}
@@ -18,6 +20,7 @@ Inject JSON data to Elasticsearch
 Options:
   -r, --refresh            Post /_refresh on the index before exit
   -d, --datastream NAME    Set op_type create instead of index
+  -e, --es-errors FILE     Write elasticsearch rejects to file
   -rt, --read-timeout SEC  Break read wait to send batch, for continuous input
   -mb, --max-bytes BYTES   Max POST _bulk size, default 10MB
   -h, --help               Display this help
@@ -32,11 +35,14 @@ REFRESH=
 DATA=
 INDEX=
 ACTION=
+ES_ERRORS=/dev/stdout
 READ_TIMEOUT=
 MAX_BYTES=$(( 10*1024*1024 ))
+
 while (( $# > 0 )); do
     case "$1" in
         -r|--refesh) REFRESH=1 ;;
+        -e|--es-errors) ES_ERRORS=$2; shift ;;
         -d|--datastream) ACTION=create ;;
         -rt|--read-timeout) READ_TIMEOUT=$2; shift ;;
         -mb|--max-bytes) MAX_BYTES=$2; shift ;;
@@ -58,6 +64,8 @@ ACTION=${ACTION:-${3:-index}}
 has_read=
 has_error=
 
+trap 'rm -f "$TEMP_FILE"' EXIT
+
 while read -r; do
     has_read=1
     {
@@ -70,16 +78,24 @@ while read -r; do
             (( bytes += (${#REPLY} + 1 + 9 + ${#ACTION}) ))
             (( bytes > MAX_BYTES )) && break
         done
-    } |
+    } > "$TEMP_FILE"
+
     es-curl "/$INDEX/_bulk" \
         -X POST -H 'Content-Type: application/x-ndjson' \
-        --data-binary @- |
-        jq -c 'if .errors then .items |to_entries[] |
-            select(.value |to_entries[] |select(.value.error))
-            else halt end'
+        --data-binary "@$TEMP_FILE" |
+    jq -c '
+if .errors then .items |to_entries[] |
+select(.value |to_entries[] |select(.value.error))
+else halt end' |
+    gawk -b '
+ARGIND==1 && match($0, /^{"key":([0-9]+),"value":(.*)}$/, cap){error[cap[1]]=cap[2]}
+ARGIND==2 && FNR%2==0 {i=int(FNR/2)-1; if (i in error) data[i]=$0}
+END{ for (i in error) printf("{\"data\":%s,\"result\":%s}\n", data[i], error[i]);
+     if (length(error) > 0) exit(1); }' - "$TEMP_FILE" >> "$ES_ERRORS"
 
     ps=${PIPESTATUS[*]}
     [[ -z ${ps//[0 ]} ]] || has_error=1
+    [[ -f "$ES_ERRORS" && ! -s "$ES_ERRORS" ]] && rm "$ES_ERRORS"
 done < <(jq -Mc . < "$DATA")
 
 [[ -z $has_read ]] && exit 2
