WIP: rsyslog: Clean rsyslog-env wrapper script

diff --git a/opt/logcenter/bin/rsyslog-env b/opt/logcenter/bin/rsyslog-env
--- a/opt/logcenter/bin/rsyslog-env
+++ b/opt/logcenter/bin/rsyslog-env
@@ -10,16 +10,10 @@ function log() {
     fi >&2
 }
 function info() { LEVEL=info log "$@"; }
-function error() { LEVEL=info log "$@"; }
-[[ -x $1 ]] || { error 'Argument is not executable'; exit 1; }
+function fatal() { LEVEL=err log "$@"; exit 1; }
+prog=$(type -P "$1")
+[[ -z $prog ]] && fatal "Executable not found: $prog"
 set -a
-source "$MAINCONF" || { error "Failed to source $MAINCONF"; exit 1; }
+source "$MAINCONF" || fatal "Source failed: $MAINCONF"
 set +a
-# cleanup potential for loop var from sourced file
-for i in $(declare -px |sed -nre 's,^declare -x ([^=]+)=.*,\1,p'); do
-    [[ $i == ${i^^} ]] && continue
-    [[ $i == *_proxy ]] && continue
-    info "Removing $i from environment"
-    unset "$i"
-done
 exec "$@"
